# Generated by Django 5.2 on 2025-06-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_doctor', models.CharField()),
                ('nombre_doctor', models.CharField(max_length=20)),
                ('apellidos_doctor', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_duenio', models.IntegerField(max_length=8)),
                ('dv_duenio', models.CharField(max_length=1)),
                ('nombre_duenio', models.CharField(max_length=20)),
                ('apellidos_duenio', models.CharField(max_length=80)),
                ('email_duenio', models.CharField(max_length=250)),
                ('celular_duenio', models.IntegerField()),
                ('fono_duenio', models.IntegerField()),
                ('direccion_duenio', models.CharField(max_length=150)),
                ('region_duenio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.IntegerField()),
                ('nombre_servicio', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sub_servicio', models.IntegerField()),
                ('nombre_sub_servicio', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mascota', models.IntegerField()),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField()),
                ('sexo_mascota', models.IntegerField(choices=[(0, 'Macho'), (1, 'Hembra')])),
                ('tipo_animal', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=80)),
                ('rut_duenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.duenio')),
            ],
        ),
    ]
