# Generated by Django 5.2 on 2025-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agenda', models.IntegerField()),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField()),
                ('sexo_mascota', models.CharField(max_length=10)),
                ('tipo_animal', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=80)),
                ('rut_dueño', models.IntegerField()),
                ('nombre_duenio', models.CharField(max_length=20)),
                ('apellido_duenio', models.CharField(max_length=250)),
                ('email_duenio', models.CharField(max_length=250)),
                ('celular_duenio', models.IntegerField()),
                ('direccion_duenio', models.CharField(max_length=150)),
                ('region_duenio', models.CharField(max_length=20)),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('nombre_sub_servicio', models.CharField(max_length=20)),
                ('fecha_agendada', models.DateField()),
                ('hora_agendada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cita', models.IntegerField()),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField()),
                ('sexo_mascota', models.CharField(max_length=10)),
                ('tipo_animal', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=80)),
                ('rut_dueño', models.IntegerField()),
                ('nombre_duenio', models.CharField(max_length=20)),
                ('apellido_duenio', models.CharField(max_length=80)),
                ('email_duenio', models.CharField(max_length=250)),
                ('celular_duenio', models.IntegerField()),
                ('direccion_duenio', models.CharField(max_length=150)),
                ('region_duenio', models.CharField(max_length=20)),
                ('nombre_servicio', models.CharField(max_length=20)),
                ('nombre_sub_servicio', models.CharField(max_length=20)),
                ('fecha_agendada_dia', models.IntegerField()),
                ('fecha_agendada_mes', models.IntegerField()),
                ('fecha_agendada_año', models.IntegerField()),
                ('hora_agendada', models.CharField(max_length=15)),
                ('hora_atendida', models.CharField(max_length=15)),
                ('nombre_especialista', models.CharField(max_length=250)),
                ('diagnostico', models.BooleanField()),
                ('receta', models.BooleanField()),
                ('insumos', models.CharField(max_length=200)),
                ('costo_promedio_medicamentos', models.IntegerField()),
                ('Tipo_costo', models.CharField(max_length=100)),
                ('insumos_costos_promedio', models.IntegerField()),
                ('ingresos_veterinaria', models.IntegerField()),
            ],
        ),
    ]
