# Generated by Django 5.2 on 2025-07-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coste_subservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coste', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rut_doctor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='duenio',
            name='rut_duenio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre_servicio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_servicio',
            name='nombre_sub_servicio',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_especialista', models.IntegerField()),
                ('nombre_especialista', models.CharField(max_length=250)),
                ('id_sub_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sub_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=250)),
                ('costo_promedio_medicamentos', models.IntegerField()),
                ('insumos_costos_promedio', models.IntegerField()),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipo_costo')),
            ],
        ),
    ]
