# Generated by Django 5.2 on 2025-07-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='apellido_duenio',
        ),
        migrations.AddField(
            model_name='agendar',
            name='tipo_edad',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='costo_servicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='diagnostico_emitido',
            field=models.CharField(default='No emitido', max_length=500),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_agenda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.agendar'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_mascota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='razon_servicio',
            field=models.CharField(default='consulta', max_length=500),
        ),
        migrations.AddField(
            model_name='cita',
            name='rut_espcialista',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiempo_espera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_edad',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
