# Generated by Django 5.2 on 2025-07-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agendar_tipo_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id_mascota',
        ),
    ]
